=== raml-apis/Wordpress/schemas/site.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "ID" : {
      "type" : "number" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "URL" : {
      "type" : "string" ,
      "required" : false
    } ,
    "jetpack" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "subscribers_count" : {
      "type" : "number" ,
      "required" : false
    } ,
    "is_private" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "is_following" : {
      "type" : "number" ,
      "required" : false
    } ,
    "meta" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "links" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "self" : {
              "type" : "string" ,
              "required" : false
            } ,
            "help" : {
              "type" : "string" ,
              "required" : false
            } ,
            "posts" : {
              "type" : "string" ,
              "required" : false
            } ,
            "comments" : {
              "type" : "string" ,
              "required" : false
            } ,
            "xmlrpc" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      }
    }
  }
}

=== raml-apis/Wordpress/examples/site.json
{
  "ID" : 3584907 ,
  "name" : "WordPress.com News" ,
  "description" : "The latest news on WordPress.com and the WordPress community." ,
  "URL" : "http://en.blog.wordpress.com" ,
  "jetpack" : false ,
  "subscribers_count" : 10541605 ,
  "is_private" : false ,
  "is_following" : 0 ,
  "meta" : {
    "links" : {
      "self" : "https://public-api.wordpress.com/rest/v1/sites/3584907" ,
      "help" : "https://public-api.wordpress.com/rest/v1/sites/3584907/help" ,
      "posts" : "https://public-api.wordpress.com/rest/v1/sites/3584907/posts/" ,
      "comments" : "https://public-api.wordpress.com/rest/v1/sites/3584907/comments/" ,
      "xmlrpc" : "https://en.blog.wordpress.com/xmlrpc.php"
    }
  }
}
